model:
  _convert_: all
  img_size:
  - 224
  - 224
  max_label_length: 25
  charset_train: 0123456789abcdefghijklmnopqrstuvwxyz
  charset_test: 0123456789abcdefghijklmnopqrstuvwxyz
  batch_size: 256
  weight_decay: 0.0
  warmup_pct: 0.075
  name: parclip
  _target_: strhub.models.parclip.system.PARCLIP
  patch_size:
  - 4
  - 8
  embed_dim: 512
  enc_num_heads: 8
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_num_heads: 8
  dec_mlp_ratio: 4
  dec_depth: 1
  lr: 0.0002
  perm_num: 6
  perm_forward: false
  perm_mirrored: false
  dropout: 0.1
  decode_ar: false
  refine_iters: 0
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: data
  train_dir: real
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 8
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 500
  max_epochs: 20
  gradient_clip_val: 20
  accelerator: gpu
  devices: 8
ckpt_path: null
pretrained: null
